services:
  teammate-go:
    container_name: teammate-go
    # image: kotvkvante/teammage-go
    build:
      context: .
      dockerfile: docker/db/Dockerfile

    # environment:
      # DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8085:8085"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile

    container_name: db
    # image: postgres:17
    environment:
      POSTGRES_PASSWORD: 111
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
